services:
  app:
    build: https://github.com/LacyAttorney599/fast_api_mealie.git#main
    ports:
      - "8000:8000"
    environment:
      MEALIE_BASE_URL: ${MEALIE_BASE_URL}
      MEALIE_API_TOKEN: ${MEALIE_API_TOKEN}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-qwen2.5:3b}
    restart: unless-stopped
